@include('partials.inputs.string',['name' => 'name','required' => true])
@include('partials.inputs.select',['singular' => 'tag_category','plural' => 'tagCategories','list' => $categories,'with_none' => true])
@include('partials.inputs.color',['type' => 'text'])
@include('partials.inputs.color',['type' => 'background'])
@include('partials.inputs.color',['type' => 'border'])
