@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'name'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'repo_url'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'demo_url'])
@include('partials.page_elements.data.label',['type' => 'features','data' => 'plural'])
@include('partials.page_elements.data.label',['type' => 'tags','data' => 'plural'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'note'])
