@include('partials.inputs.string',['name' => 'title','required' => true])
@include('partials.inputs.string',['name' => 'company','required' => true])
@include('partials.inputs.string',['name' => 'address'])
@include('partials.inputs.url',['name' => 'article'])
@include('partials.inputs.url',['name' => 'website'])
@include('partials.inputs.email')
@include('partials.inputs.phone')
@include('partials.inputs.string',['name' => 'person'])
@include('partials.inputs.date',['type' => 'apply'])
@include('partials.inputs.select',['name' => 'jobsearch_type','list' => $types,'required' => true])
@include('partials.inputs.select',['name' => 'jobsearch_status','list' => $statuses,'required' => true])
