@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'name'])
@include('partials.page_elements.data.label',['type' => 'certificateIssuers','data' => 'singular'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'earn_date'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'expire_date'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'file'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'note'])
