@include('partials.inputs.string',['name' => 'name','required' => true])
@include('partials.inputs.select',['name' => 'experience_type','list' => $types,'required' => true])
@include('partials.inputs.string',['name' => 'location','required' => true])
@include('partials.inputs.date',['type' => 'start','required' => true])
@include('partials.inputs.date',['type' => 'end','required' => true])
@include('partials.inputs.textarea',['name' => 'note'])
