@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'name'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'location'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'type'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'start_date'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'end_date'])
@include('partials.page_elements.data.label',['type' => 'inputs','data' => 'note'])
